MODEL_PATH: ./trained_models/vww_96.h5
IMAGE_SIZE: 96
BATCH_SIZE: 32
EPOCHS: 100
BASE_DIR: ./retrain_images/mnist
LEARNING_RATE: 0.0001

# conv2d layers : [1, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79]
# depthwise conv2d layer: [4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76]
# dense layer : [84]

TRAINABLE_LAYERS:
  - 19
  - 29
  - 37
  - 40

EARLY_STOPPING:
  ENABLED: true
  MONITOR: "val_accuracy"
  PATIENCE: 5
  MIN_DELTA: 0.0001
  MODE: "max"
  RESTORE_BEST_WEIGHTS: true